Uni.PLL/Controllers/RolesController.cs
using Uni.DAL.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Uni.BLL.ModelVM.Admin;
//using Newtonsoft.Json;

namespace Uni.PLL.Controllers
{
    // role for (admin ,user)

    // [Authorize (Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<Student> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(UserManager<Student> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var _users = await _userManager.Users.ToListAsync();
            return View(_users);
        }

        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var userRoles = await _userManager.GetRolesAsync(user);

            var allRoles = await _roleManager.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new RoleVM()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _userManager.FindByIdAsync(userId);

            List<RoleVM> myRoles = JsonConvert.DeserializeObject<List<RoleVM>>(jsonRoles);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _userManager.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _userManager.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Uni.PLL/Views/Roles/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@using Uni.BLL.ModelVM;
@model IEnumerable<IdentityUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container p-3">


    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">System Users</h2>
        </div>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">
                    User Id
                </th>
                <th scope="col">
                    User Name
                </th>
                <th scope="col">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-primary">
                    <td scope="row" width="30%">
                        @item.Id
                    </td>
                    <td>
                        @item.UserName
                    </td>
                    <td>
                        <a asp-controller="Roles" asp-action="addRoles" asp-route-userId="@item.Id" class="btn btn-sm btn-success">
                            <i class="bi bi-pencil"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>

        function readTableToArr() {
            var arr = [];
            var JsData = "";

            $("#roleTable tbody tr").each(function (index, data) {

                const roleId = $(data).find(".tId").text();
                const roleName = $(data).find(".tName").text();
                const useRole = $(data).find(".tCheck").is(":checked");

                arr.push({
                    roleId: roleId,
                    roleName: roleName,
                    useRole: useRole
                });
            });
            return JSON.stringify(arr);
        }

        function updateJsonFile() {

            $("#jsonRoles").val(readTableToArr());
        }
    </script>
}

Uni.PLL/Views/Roles/addRoles.cshtml
@using Uni.BLL.ModelVM.Admin;
@model IEnumerable<RoleVM>
@{
    ViewData["Title"] = "addRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">User Role</h2>
               @*  <h3>ViewBag.userName</h3> *@
            </div>
        </div>

        <input hidden id="userName" name="userName" value="@ViewBag.userName" />
        <input hidden id="userId" name="userId" value="@ViewBag.userId" />
        <input hidden id="jsonRoles" name="jsonRoles" />

        <table id="roleTable" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">
                        Role Id
                    </th>
                    <th scope="col">
                        Role Name
                    </th>
                    <th scope="col">
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="table-primary">
                        <td scope="row" class="tId" width="30%">
                            @item.roleId
                        </td>
                        <td class="tName">
                            @item.roleName
                        </td>
                        <td>
                            <input type="checkbox" class="tCheck" @(item.useRole ? "checked" : "") />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <button type="submit" onclick="updateJsonFile()" class="btn btn-primary" style="width:150px">Save</button>
</form>




@section Scripts {
    <script>

        function readTableToArr() {
            var arr = [];
            var JsData = "";

            $("#roleTable tbody tr").each(function (index, data) {

                const roleId = $(data).find(".tId").text();
                const roleName = $(data).find(".tName").text();
                const useRole = $(data).find(".tCheck").is(":checked");

                arr.push({
                    roleId: roleId,
                    roleName: roleName,
                    useRole: useRole
                });
            });
            return JSON.stringify(arr);
        }

        function updateJsonFile() {

            $("#jsonRoles").val(readTableToArr());
        }
    </script>
}